[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_ENV = "production"

[context.deploy-preview.environment]
  REACT_APP_ENV = "preview"

[context.branch-deploy.environment]
  REACT_APP_ENV = "development"
